title: My Home Assistant smart heating configuration
lang: en
description: My configuration for smart heating thermostat with the use of Home Assistant. 

#markdown: kramdown

remote_theme: rundocs/jekyll-rtd-theme

#kramdown:
#  toc_levels: 3
#  parse_block_html: true

readme_index:
   with_frontmatter: true
   
plugins:
  - jekyll-readme-index
  - jekyll-numbered-headings

google:
  gtag: G-ERSFN94HKL
  
exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - descriptionVoorEnum.md

